import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Netra AI",
  description: "Generated by create next app",
  keywords: ["Eye AI", "Netra.AI", "AI platform"],
  authors: [{ name: "Dheeraj Appaji" }, { name: "Kshama" }, { name: "Vivin Dsouza" }],
  icons: {
    icon: "/logo.svg", // Update with your favicon path if different
  },
  openGraph: {
    title: "Meet.AI",
    description: "Create and interact with custom AI agents in seconds.",
    url: "https://meetai-pearl.vercel.app", // Replace with your real URL
    siteName: "Meet.AI",
    images: [
      {
        url: "/logo.png", // Make sure this image exists in your public/ folder
        width: 1200,
        height: 630,
        alt: "Meet.AI - AI Agent Platform",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster richColors />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
